export enum CommandType {
  GO_TO_LOCATION = "GO TO LOCATION",
  CATCH_FISH = "CATCH FISH",
  START_FISHING = "START FISHING",
  START_PICKING_FOREST_FRUITS = "START PICKING FOREST FRUITS",
  TAKE_FRUITS_OF_THE_FOREST = "TAKE FRUITS OF THE FOREST",
  ASK_BEAVER_TO_REBUILD_DAM = "ASK BEAVER TO REBUILD DAM",
  EXCHANGE = "EXCHANGE"
}

export const GO_TO_LOCATION = CommandType.GO_TO_LOCATION;
export const CATCH_FISH = CommandType.CATCH_FISH;
export const START_FISHING = CommandType.START_FISHING;
export const START_PICKING_FOREST_FRUITS = CommandType.START_PICKING_FOREST_FRUITS;
export const TAKE_FRUITS_OF_THE_FOREST = CommandType.TAKE_FRUITS_OF_THE_FOREST;
export const ASK_BEAVER_TO_REBUILD_DAM = CommandType.ASK_BEAVER_TO_REBUILD_DAM;
export const EXCHANGE = CommandType.EXCHANGE;
