export enum EventType {
  WENT_TO_LOCATION = "WENT TO LOCATION",
  FISH_CATCHED = "FISH CATCHED",
  FISHING_STARTED = "FISHING STARTED",
  PICKING_FOREST_FRUITS_STARTED = "PICKING FOREST FRUITS STARTED",
  FRUITS_OF_THE_FOREST_TAKEN = "FRUITS OF THE FOREST TAKEN",
  GOLDEN_COIN_EARNED = "GOLDEN COIN EARNED"
}

export const WENT_TO_LOCATION = EventType.WENT_TO_LOCATION;
export const FISH_CATCHED = EventType.FISH_CATCHED;
export const FISHING_STARTED = EventType.FISHING_STARTED;
export const PICKING_FOREST_FRUITS_STARTED = EventType.PICKING_FOREST_FRUITS_STARTED;
export const FRUITS_OF_THE_FOREST_TAKEN = EventType.FRUITS_OF_THE_FOREST_TAKEN;
export const GOLDEN_COIN_EARNED = EventType.GOLDEN_COIN_EARNED;
