export enum EventType {
  WENT_TO_LOCATION = "WENT TO LOCATION",
  FISH_CATCHED = "FISH CATCHED",
  FISHING_STARTED = "FISHING STARTED"
}

export const WENT_TO_LOCATION = EventType.WENT_TO_LOCATION;
export const FISH_CATCHED = EventType.FISH_CATCHED;
export const FISHING_STARTED = EventType.FISHING_STARTED;
